"""
Unit tests for POST /v1/messages (api-core) — C2-T05.

Verifies that the endpoint:
  - publishes exactly one ProcessingTask to tasks.processing via the bus
  - returns {task_id, status='queued'} with the same task_id
  - returns 422 for structurally invalid bodies (missing required fields)
  - guarantees user_id is populated (stub resolve — Q-C2-3)

The MessageBus is replaced with InMemoryBus via DI override so no real
broker is needed. The DB probe is also overridden to avoid needing Postgres.

LLM/OFF are not involved in C2 — nothing to mock there.
"""

from __future__ import annotations

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture()
async def api_client_with_inmemory_bus():
    """
    ASGI test client for api-core where:
    - DB probe is overridden with a no-op (unit test, no real Postgres needed)
    - MessageBus is overridden with InMemoryBus (no real Redis needed)

    Returns (client, bus) so tests can inspect what was published.
    """
    from apps.api_core.bus_provider import get_bus
    from apps.api_core.health import get_db_probe
    from apps.api_core.main import app
    from core.bus import InMemoryBus

    bus = InMemoryBus()

    async def _noop_db_probe() -> None:
        return None

    def _db_probe_dep():
        return _noop_db_probe

    def _bus_dep():
        return bus

    app.dependency_overrides[get_db_probe] = _db_probe_dep
    app.dependency_overrides[get_bus] = _bus_dep

    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        yield client, bus

    app.dependency_overrides.clear()


# ---------------------------------------------------------------------------
# Happy path: valid body → 200/202 + queued + exactly one task published
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_post_messages_valid_body_returns_queued_status(api_client_with_inmemory_bus):
    """
    POST /v1/messages with a valid body must return HTTP 200 (or 202) and a
    JSON body containing status='queued'.
    This confirms the endpoint enqueues the task and responds immediately
    without waiting for processing (contracts.md §1.2, ADR-0003).
    """
    client, _bus = api_client_with_inmemory_bus

    payload = {
        "channel": "telegram",
        "channel_user_id": "12345",
        "text": "200г жареной курицы",
        "reply_to": {"chat_id": 99, "message_id": 7},
    }
    response = await client.post("/v1/messages", json=payload)

    assert response.status_code in (200, 202)
    data = response.json()
    assert data["status"] == "queued"


@pytest.mark.asyncio
async def test_post_messages_response_contains_task_id(api_client_with_inmemory_bus):
    """
    POST /v1/messages response must include a non-empty task_id string.
    The caller (channel adapter) uses task_id for tracing; it must be
    generated by api-core and returned in the response (contracts.md §1.2,
    ADR-0017 traceability).
    """
    client, _bus = api_client_with_inmemory_bus

    payload = {
        "channel": "telegram",
        "channel_user_id": "12345",
        "text": "тарелка борща",
        "reply_to": {"chat_id": 1},
    }
    response = await client.post("/v1/messages", json=payload)

    data = response.json()
    assert "task_id" in data
    assert isinstance(data["task_id"], str)
    assert len(data["task_id"]) > 0


@pytest.mark.asyncio
async def test_post_messages_publishes_exactly_one_task(api_client_with_inmemory_bus):
    """
    POST /v1/messages must publish exactly one ProcessingTask to the
    tasks.processing topic — no double-publish, no partial publish.
    api-core is the sole publisher of tasks.processing (ADR-0012).
    """
    client, bus = api_client_with_inmemory_bus

    published: list[dict] = []

    async def capture_handler(event: dict) -> None:
        published.append(event)

    from core.bus import InMemoryBus

    assert isinstance(bus, InMemoryBus)
    await bus.subscribe("tasks.processing", "test-capture", capture_handler)

    payload = {
        "channel": "telegram",
        "channel_user_id": "12345",
        "text": "яблоко",
        "reply_to": {"chat_id": 1},
    }
    await client.post("/v1/messages", json=payload)

    # Drive the bus to deliver to our capture handler
    import asyncio
    await asyncio.sleep(0)

    assert len(published) == 1, (
        f"Expected exactly 1 ProcessingTask in tasks.processing, got {len(published)}"
    )


@pytest.mark.asyncio
async def test_post_messages_task_text_matches_request(api_client_with_inmemory_bus):
    """
    The ProcessingTask published to tasks.processing must carry the same
    text as provided in the POST body.
    Verifies data fidelity from HTTP boundary to broker event
    (contracts.md §3.1).
    """
    client, bus = api_client_with_inmemory_bus

    published: list[dict] = []

    async def capture_handler(event: dict) -> None:
        published.append(event)

    from core.bus import InMemoryBus

    assert isinstance(bus, InMemoryBus)
    await bus.subscribe("tasks.processing", "test-capture-2", capture_handler)

    original_text = "300г овсянки на молоке"
    payload = {
        "channel": "telegram",
        "channel_user_id": "12345",
        "text": original_text,
        "reply_to": {"chat_id": 1},
    }
    await client.post("/v1/messages", json=payload)

    import asyncio
    await asyncio.sleep(0)

    assert published[0].get("text") == original_text


@pytest.mark.asyncio
async def test_post_messages_task_id_matches_response_task_id(api_client_with_inmemory_bus):
    """
    The task_id returned in the HTTP response must equal the task_id carried
    in the ProcessingTask published to tasks.processing — they must not diverge.
    This is the fundamental correlation guarantee (ADR-0017, TДЕ-6).
    """
    client, bus = api_client_with_inmemory_bus

    published: list[dict] = []

    async def capture_handler(event: dict) -> None:
        published.append(event)

    from core.bus import InMemoryBus

    assert isinstance(bus, InMemoryBus)
    await bus.subscribe("tasks.processing", "test-capture-3", capture_handler)

    payload = {
        "channel": "telegram",
        "channel_user_id": "u99",
        "text": "бутерброд с маслом",
        "reply_to": {"chat_id": 5},
    }
    response = await client.post("/v1/messages", json=payload)

    import asyncio
    await asyncio.sleep(0)

    response_task_id = response.json()["task_id"]
    published_task_id = published[0]["task_id"]

    assert response_task_id == published_task_id, (
        f"HTTP response task_id={response_task_id!r} differs from "
        f"published ProcessingTask task_id={published_task_id!r} "
        "(must be identical — TДЕ-6 correlation guarantee)"
    )


@pytest.mark.asyncio
async def test_post_messages_task_user_id_is_set(api_client_with_inmemory_bus):
    """
    The ProcessingTask published to tasks.processing must have user_id set to
    a non-None integer (stub resolve — Q-C2-3).
    Real user resolution comes in C6; for C2 the stub must be deterministic
    and produce an int (not None, not a UUID string).
    """
    client, bus = api_client_with_inmemory_bus

    published: list[dict] = []

    async def capture_handler(event: dict) -> None:
        published.append(event)

    from core.bus import InMemoryBus

    assert isinstance(bus, InMemoryBus)
    await bus.subscribe("tasks.processing", "test-capture-uid", capture_handler)

    payload = {
        "channel": "telegram",
        "channel_user_id": "u1",
        "text": "кефир",
        "reply_to": {"chat_id": 1},
    }
    await client.post("/v1/messages", json=payload)

    import asyncio
    await asyncio.sleep(0)

    user_id = published[0].get("user_id")
    assert user_id is not None, "user_id must be set in the published ProcessingTask"
    assert isinstance(user_id, int), f"user_id must be int, got {type(user_id)}"


# ---------------------------------------------------------------------------
# Validation: invalid body → 422, structured JSON, no stack trace
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_post_messages_missing_text_returns_422(api_client_with_inmemory_bus):
    """
    POST /v1/messages without the required 'text' field must return HTTP 422.
    The endpoint must validate the request body against IngestMessageRequest
    and return a structured validation error (conventions §5).
    """
    client, _bus = api_client_with_inmemory_bus

    payload = {
        "channel": "telegram",
        "channel_user_id": "12345",
        # 'text' is intentionally missing
        "reply_to": {"chat_id": 1},
    }
    response = await client.post("/v1/messages", json=payload)

    assert response.status_code == 422


@pytest.mark.asyncio
async def test_post_messages_missing_channel_returns_422(api_client_with_inmemory_bus):
    """
    POST /v1/messages without the required 'channel' field must return HTTP 422.
    Ensures all required fields of IngestMessageRequest are enforced at the
    HTTP boundary (conventions §5).
    """
    client, _bus = api_client_with_inmemory_bus

    payload = {
        # 'channel' is intentionally missing
        "channel_user_id": "12345",
        "text": "обед",
        "reply_to": {"chat_id": 1},
    }
    response = await client.post("/v1/messages", json=payload)

    assert response.status_code == 422


@pytest.mark.asyncio
async def test_post_messages_422_body_is_structured_json_without_traceback(
    api_client_with_inmemory_bus,
):
    """
    The 422 response body must be valid, structured JSON and must not expose
    Python stack traces or internal exception details.
    Prevents information leakage at the HTTP boundary (conventions §5).
    """
    client, _bus = api_client_with_inmemory_bus

    payload = {}  # completely empty — all required fields missing
    response = await client.post("/v1/messages", json=payload)

    assert response.status_code == 422
    data = response.json()
    assert isinstance(data, dict), "422 body must be a JSON object"

    body_text = str(data)
    assert "Traceback" not in body_text, "Stack trace must not appear in 422 response"
    assert "Exception" not in body_text, "Exception class must not appear in 422 response"
